### ISSUE TITLE
Rename this repo - right?

### ISSUE THREAD

**Issue by consideRatio** [2i2c-org/default-hub-homepage#12]
### Background and proposal

I'm not confident what this repo is about, but it includes pilot in its name. Rename it?

Ping @2i2c-org/tech-team

**Comment by yuvipanda** [comment]
Yep. Probably default-hub-homepage

**Comment by consideRatio** [comment]
That name clarifies a lot better what this is about to me! Nice okay!

See https://github.com/2i2c-org/infrastructure/pull/1134

**Comment by yuvipanda** [comment]
Renamed!
